why we use numpy?otherthan list?

lists are very slow where as numpy is fast compared to list
arrays are stored at a continuous placein memory  


Numpy is a python library used for working with arrays

In [1]:
import numpy as np
print(np.__version__)

1.19.2


In [5]:
#creating arrays
## zero dimensional
a=np.array(3)
print(a)
## one dimensional
b=np.array([10,20,30])
print(b)
## two dimensional
c=np.array([[10,20],[30,40]])
print(c)
## three diminisional
d=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(d)

3
[10 20 30]
[[10 20]
 [30 40]]
[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [8]:
##asarray() with nditer

a=[10,20,30]
b=np.asarray(a,dtype=float)
print(b)

[10. 20. 30.]


In [13]:
a=[10,20,30],[30,40,60]
b=np.asarray(a,order='c')   #'c' ROW  major order
print(b)
for i in np.nditer(b):
    print(i)


[[10 20 30]
 [30 40 60]]
10
20
30
30
40
60


In [14]:
a=[10,20,30],[30,40,60]
b=np.asarray(a,order='F')   # 'F'coloum major order
print(b)
for i in np.nditer(b):
    print(i)


[[10 20 30]
 [30 40 60]]
10
30
20
40
30
60


In [20]:
#frombuffer
a=b'lucky is a good boy'
np.frombuffer(a,dtype="S1")
#np.frombuffer(a,dtype="S1",count=2) 
#np.frombuffer(a,dtype="S1",offset=3) (strating)

array([b'k', b'y', b' ', b'i', b's', b' ', b'a', b' ', b'g', b'o', b'o',
       b'd', b' ', b'b', b'o', b'y'], dtype='|S1')

In [2]:
#fromiter used to convert sequence to array
a=[1,2,3,4]
np.fromiter(a,dtype=int) 
#dtype is must for fromiter

array([1, 2, 3, 4])

**initializing array


In [28]:
#zeroes() function
a=np.zeros(4)
print(a)
b=np.zeros([3,3])
print(b)
c=np.zeros([2,2,2])
print(c)


[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [30]:
#full() function
a=np.full([3 ,3],10)
print(a)
# one must be dimension another will be substituted value

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [34]:
#random.rand
a=np.random.rand(2,3)
print(a)

[[0.10383705 0.64296219 0.063478  ]
 [0.05219972 0.37952353 0.89764607]]


In [35]:
#ones
a=np.ones([2,3])
print(a)
#total numbers ar appeared wit float

[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
a=np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


**NUMERICAL RANGE

In [83]:
#arange
a=np.arange(10,14,1)
print(a)
c=a.reshape(2,2)
print(c)
b=np.arange(10,15,1,dtype=float)
print(b)



[10 11 12 13]
[[10 11]
 [12 13]]
[10. 11. 12. 13. 14.]


In [54]:
#linespace
a=np.linspace(0,10,5,endpoint=False,retstep=True)
print(a)
#endpoint is for removing end values
#retstep is for difference values
#here in this "5" is used as intervals

(array([0., 2., 4., 6., 8.]), 2.0)


In [57]:
#logspace
a=np.logspace(1,10,10,base=2)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


**array properties

In [63]:
a=np.arange(10,100,10)
b=a.reshape(3,3)
print(b)
np.size(b)    # size
b.dtype        #type array.dtype


[[10 20 30]
 [40 50 60]
 [70 80 90]]


dtype('int32')

In [64]:
arr=np.array([1,2,3,4,5])
print(arr[0]+arr[4])      #adding elements in array

6


In [65]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


**SLICING

In [80]:
a=np.array([1,2,3,4,5,6,7])
print(a[1:5])
print(a[:4])
print(a[4:])

[2 3 4 5]
[1 2 3 4]
[5 6 7]


In [81]:
a=np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(a[1,1:4])

[4 5 6]


In [3]:
#astype is used to convert from int to bool
a=np.array([1,0,1])
new=a.astype(bool)
print(new)


[ True False  True]


In [86]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[4,5,6,7],[3,5,6,7]]])
print(a)

[[[1 2 3 4]
  [5 6 7 8]]

 [[4 5 6 7]
  [3 5 6 7]]]


In [89]:
#sort()
a=np.array([1,9,8,6,5,4])
np.sort(a)


array([1, 4, 5, 6, 8, 9])

In [99]:
a=np.array([[90,50,40],[10,15,11]])
np.sort(a,axis=0)
#axis=0 is used to sort column
#axis=1 row wise sort


array([[10, 15, 11],
       [90, 50, 40]])

In [101]:
#append
a=np.array([[90,50,40],[10,15,11]])
b=np.array([[90,50,40],[10,15,11]])
np.append(a,b)

array([90, 50, 40, 10, 15, 11, 90, 50, 40, 10, 15, 11])

In [102]:
#insert
a=np.array([[90,50,40],[10,15,11]])
np.insert(a,5,99)

array([90, 50, 40, 10, 15, 99, 11])

In [103]:
#delete
a=np.array([[90,50,40],[10,15,11]])
np.delete(a,5)

array([90, 50, 40, 10, 15])

**joining

In [106]:
#concatenate
a=np.array([[90,50,40],[10,15,11]])
b=np.array([[90,50,40],[10,15,11]])
np.concatenate((a,b))

array([[90, 50, 40],
       [10, 15, 11],
       [90, 50, 40],
       [10, 15, 11]])

In [107]:
#stack
a=np.array([[90,50,40],[10,15,11]])
b=np.array([[90,50,40],[10,15,11]])
np.stack((a,b))
#it doesn't merge a,b but it shows different arrays

array([[[90, 50, 40],
        [10, 15, 11]],

       [[90, 50, 40],
        [10, 15, 11]]])

In [108]:
#hstack()
a=np.array([[90,50,40],[10,15,11]])
b=np.array([[90,50,40],[10,15,11]])
np.hstack((a,b))
#along rows

array([[90, 50, 40, 90, 50, 40],
       [10, 15, 11, 10, 15, 11]])

In [109]:
#vstack
a=np.array([[90,50,40],[10,15,11]])
b=np.array([[90,50,40],[10,15,11]])
np.vstack((a,b))
#along columns

array([[90, 50, 40],
       [10, 15, 11],
       [90, 50, 40],
       [10, 15, 11]])

In [110]:
#dstack
a=np.array([[90,50,40],[10,15,11]])
b=np.array([[90,50,40],[10,15,11]])
np.dstack((a,b))
#alon height

array([[[90, 90],
        [50, 50],
        [40, 40]],

       [[10, 10],
        [15, 15],
        [11, 11]]])

**splitting

In [117]:
#spilt
a=np.arange(10,110,10)
np.split(a,5)


[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

**searching arrays

In [118]:
#where
a=np.arange(10,110,10)
np.where(a==80)

(array([7], dtype=int64),)

In [122]:
a=np.arange(10,110,10).reshape(5,2)

np.where(a%20==0)
# for multible dimensions we should se top and bottom

(array([0, 1, 2, 3, 4], dtype=int64), array([1, 1, 1, 1, 1], dtype=int64))

In [124]:
#searchsorted
a=np.arange(10,110,10)
#np.searchsorted(a,60)
#use full to find index
np.searchsorted(a,[60,80])
#for more than 2 number search we should use '[]'

array([5, 7], dtype=int64)

**ARITHMETIC OPERATION

In [125]:
#add
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[40,50,60]])
np.add(a,b)


array([[11, 22, 33],
       [44, 55, 66]])

In [126]:
#subtract
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[40,50,60]])
np.subtract(a,b)

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [127]:
#multiply
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[40,50,60]])
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 360]])

In [128]:
#divide
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[40,50,60]])
np.divide(a,b)

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [130]:
#sqrt
a=np.array([[1,2,3],[4,5,6]])
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [131]:
#comparision
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[40,50,60]])
np.array_equal(a,b)
#if those two are not equal shows false

False

In [132]:
#min
a=np.array([[1,2,3],[4,5,6]])
np.min(a,axis=1)
#row wise

array([1, 4])

In [133]:
#max
a=np.array([[1,2,3],[4,5,6]])
np.max(a,axis=1)

array([3, 6])

In [134]:
#sum
a=np.array([[1,2,3],[4,5,6]])
np.sum(a,axis=1)

array([ 6, 15])

In [136]:
#mean
a=np.array([[1,2,3],[4,5,6]])
np.mean(a,axis=1)


array([2., 5.])

In [138]:
#median
a=np.array([[1,2,3],[4,5,6]])
np.median(a,axis=1)

array([2., 5.])

In [3]:
#variance
a=np.array([[1,2,3],[4,5,6]])
np.var(a,axis=1)

array([0.66666667, 0.66666667])

In [140]:
#standerd deviation
a=np.array([[1,2,3],[4,5,6]])
np.std(a,axis=1)

array([0.81649658, 0.81649658])